# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.Z3
PackageVersion: 5.1.0
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-08-16
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: z3-5.1.0-x64-win\bin\z3.exe
    PortableCommandAlias: z3
  InstallerUrl: https://github.com/Z3Prover/z3/releases/download/z3-5.1.0/z3-5.1.0-x64-win.zip
  InstallerSha256: 6FF368EAA2F9DC18ACF244E736A074DF877026BFC83ABEDE6F327EBB95680535
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: z3-5.1.0-arm64-win\bin\z3.exe
    PortableCommandAlias: z3
  InstallerUrl: https://github.com/Z3Prover/z3/releases/download/z3-5.1.0/z3-5.1.0-arm64-win.zip
  InstallerSha256: 82A21C5526EF47DF895F43734AAEA163CAF92CE772502235817BCFC8DAADCB40
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: z3-5.1.0-x86-win\bin\z3.exe
    PortableCommandAlias: z3
  InstallerUrl: https://github.com/Z3Prover/z3/releases/download/z3-5.1.0/z3-5.1.0-x86-win.zip
  InstallerSha256: 0E8CE9CDCFA5650FEF7B72234656E12D23D28C34035C6A61E6F55432B99FBE07
ManifestType: installer
ManifestVersion: 1.12.0
